// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLcEIOIW7ftDr6-C7uhtPGnL4AqBrfHG8',
    appId: '1:640646199364:android:c956ec39e9521b25fca411',
    messagingSenderId: '640646199364',
    projectId: 'simpleapp-5c1c6',
    storageBucket: 'simpleapp-5c1c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVbMYfdSAEYfKXbP706KC66iZIx79Qyhc',
    appId: '1:640646199364:ios:4667a78a84127c29fca411',
    messagingSenderId: '640646199364',
    projectId: 'simpleapp-5c1c6',
    storageBucket: 'simpleapp-5c1c6.firebasestorage.app',
    androidClientId: '640646199364-1spmrgked6bc56mrn0qnkl0nurbbaj72.apps.googleusercontent.com',
    iosClientId: '640646199364-at26bdjg6u5dt43dt5jhf1qeerqq14en.apps.googleusercontent.com',
    iosBundleId: 'com.mangalounge.memberapp',
  );

}