/// Centralized Dependency Injection using Riverpod
///
/// This file contains all Riverpod providers for the application.
/// Providers are organized by feature (auth, user, etc.)
///
/// Provider dependency tree:
/// - Data Sources (lowest level - talks to Firebase)
/// - Repositories (uses Data Sources)
/// - Use Cases (uses Repositories)
/// - State Notifiers (uses Use Cases)
library;

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart' as firebase_auth;
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../features/auth/data/datasources/auth_datasource.dart';
import '../../features/auth/data/repositories/auth_repository_impl.dart';
import '../../features/auth/domain/repositories/auth_repository.dart';
import '../../features/auth/domain/usecases/auth_usecases.dart';
import '../../features/user/data/datasources/user_datasource.dart';
import '../../features/user/data/repositories/user_repository_impl.dart';
import '../../features/user/domain/repositories/user_repository.dart';
import '../../features/user/domain/usecases/user_usecases.dart';

// ============================================================================
// AUTH FEATURE PROVIDERS
// ============================================================================

/// Auth Data Source Provider
/// Provides Firebase implementation of AuthDataSource
final authDataSourceProvider = Provider<AuthDataSource>((ref) {
  return FirebaseAuthDataSource();
});

/// Auth Repository Provider
/// Provides implementation of AuthRepository using AuthDataSource
final authRepositoryProvider = Provider<AuthRepository>((ref) {
  return AuthRepositoryImpl(ref.watch(authDataSourceProvider));
});

// ============================================================================
// AUTH USE CASE PROVIDERS
// ============================================================================

/// SendOTP Use Case Provider
final sendOTPProvider = Provider<SendOTP>((ref) {
  return SendOTP(ref.watch(authRepositoryProvider));
});

/// VerifyOTP Use Case Provider
final verifyOTPProvider = Provider<VerifyOTP>((ref) {
  return VerifyOTP(ref.watch(authRepositoryProvider));
});

/// SignOut Use Case Provider
final signOutProvider = Provider<SignOut>((ref) {
  return SignOut(ref.watch(authRepositoryProvider));
});

/// WatchAuthState Use Case Provider
final watchAuthStateProvider = Provider<WatchAuthState>((ref) {
  return WatchAuthState(ref.watch(authRepositoryProvider));
});

/// GetCurrentUserId Use Case Provider
final getCurrentUserIdProvider = Provider<GetCurrentUserId>((ref) {
  return GetCurrentUserId(ref.watch(authRepositoryProvider));
});

// ============================================================================
// AUTH STATE NOTIFIER PROVIDER
// ============================================================================

/// Auth State Notifier Provider
/// Manages authentication state for the entire app
///
/// Now auto-generated by Riverpod codegen from:
/// lib/features/auth/presentation/providers/auth_state_notifier.dart
/// Access via: authStateProvider

// ============================================================================
// FIREBASE PROVIDERS (Shared across features)
// ============================================================================

/// Firebase Auth Provider
final firebaseAuthProvider = Provider<firebase_auth.FirebaseAuth>((ref) {
  return firebase_auth.FirebaseAuth.instance;
});

/// Firestore Provider
final firestoreProvider = Provider<FirebaseFirestore>((ref) {
  return FirebaseFirestore.instance;
});

// ============================================================================
// USER FEATURE PROVIDERS
// ============================================================================

/// User Data Source Provider
/// Provides Firestore implementation of UserDataSource
final userDataSourceProvider = Provider<UserDataSource>((ref) {
  return UserDataSourceImpl(
    firestore: ref.watch(firestoreProvider),
    auth: ref.watch(firebaseAuthProvider),
  );
});

/// User Repository Provider
/// Provides implementation of UserRepository using UserDataSource
final userRepositoryProvider = Provider<UserRepository>((ref) {
  return UserRepositoryImpl(ref.watch(userDataSourceProvider));
});

// ============================================================================
// USER USE CASE PROVIDERS
// ============================================================================

/// CreateUserProfile Use Case Provider
final createUserProfileProvider = Provider<CreateUserProfile>((ref) {
  return CreateUserProfile(ref.watch(userRepositoryProvider));
});

/// GetUser Use Case Provider
final getUserProvider = Provider<GetUser>((ref) {
  return GetUser(ref.watch(userRepositoryProvider));
});

/// GetCurrentUser Use Case Provider
final getCurrentUserProvider = Provider<GetCurrentUser>((ref) {
  return GetCurrentUser(ref.watch(userRepositoryProvider));
});

/// UpdateUserProfile Use Case Provider
final updateUserProfileProvider = Provider<UpdateUserProfile>((ref) {
  return UpdateUserProfile(ref.watch(userRepositoryProvider));
});

/// CheckUserProfileExists Use Case Provider
final checkUserProfileExistsProvider = Provider<CheckUserProfileExists>((ref) {
  return CheckUserProfileExists(ref.watch(userRepositoryProvider));
});

/// WatchUser Use Case Provider
final watchUserProvider = Provider<WatchUser>((ref) {
  return WatchUser(ref.watch(userRepositoryProvider));
});

/// UpdateUserStatus Use Case Provider
final updateUserStatusProvider = Provider<UpdateUserStatus>((ref) {
  return UpdateUserStatus(ref.watch(userRepositoryProvider));
});

// ============================================================================
// USER STATE NOTIFIER PROVIDER
// ============================================================================

/// User State Notifier Provider
/// Manages user state for the entire app
///
/// Now auto-generated by Riverpod codegen from:
/// lib/features/user/presentation/providers/user_state_notifier.dart
/// Access via: userStateNotifierProvider
